export enum SaasFeature {
  /** SOLO+ (tương đương Tendoo hộ kinh doanh) */
  POS = 'POS',
  MENU = 'MENU',
  PAYMENTS = 'PAYMENTS',
  BASIC_REPORTS = 'BASIC_REPORTS',
  STORE_SETTINGS = 'STORE_SETTINGS',
  KITCHEN = 'KITCHEN',
  WAREHOUSE = 'WAREHOUSE',
  RECIPE = 'RECIPE',

  /** STORE+ (nhiều nhân viên, ca, kế toán) */
  SHIFT_MGMT = 'SHIFT_MGMT',
  ACCOUNTING = 'ACCOUNTING',
  EMPLOYEES = 'EMPLOYEES',
  FULL_DASHBOARD = 'FULL_DASHBOARD',

  /** CHAIN / Premium */
  MULTI_BRANCH = 'MULTI_BRANCH',
  CRM = 'CRM',
  LOYALTY = 'LOYALTY',
  MARKETING = 'MARKETING',
  API_INTEGRATION = 'API_INTEGRATION',
  KIOSK = 'KIOSK',
  ADVANCED_ANALYTICS = 'ADVANCED_ANALYTICS',
}
